project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Agriculture
        menu:
          - href: MineralFert.qmd
            text: Mineral Fertilization Emissions
          - href: UreaEmissions.qmd
            text: Urea Fertilization Emissions
          - href: MonteCarlo.qmd
            text: Advanced Monte Carlo
      - text: Transportation
        menu:
          - href: Transport.qmd
            text: Transportation Emissions
          - href: GreenTransport.qmd
            text: Green Transportation
      - text: Electricity
        menu:
          - href: Electricity1.qmd
            text: Lesson 1
          - href: Electricity2.qmd
            text: Lesson 2
      - text: Miscilaneous Skills
        menu:
          - href: EmissionFactors.qmd
            text: Emission Factors
          - href: example.qmd
            text: Lesson 2

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

