project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Agriculture
        menu:
          - href: UreaEmissions.qmd
            text: Urea Emissions Function
          - href: example.qmd
            text: Lesson 2
      - text: Transportation
        menu:
          - href: example.qmd
            text: Lesson 1
          - href: example.qmd
            text: Lesson 2
      - text: Electricity
        menu:
          - href: example.qmd
            text: Lesson 1
          - href: example.qmd
            text: Lesson 2
      - text: Miscilaneous Skills
        menu:
          - href: example.qmd
            text: Lesson 1
          - href: example.qmd
            text: Lesson 2

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

