project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: GHG
        menu:
          - href: ess-696.qmd
            text: Lesson 1
          - href: example.qmd
            text: Lesson 2
      

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

